<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\AddVideoResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/AddVideoResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/AddVideoResponder.php';

return $this->privates['App\UI\Responders\AddVideoResponder'] = new \App\UI\Responders\AddVideoResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
