<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\AddedVideoResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/AddedVideoResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/AddedVideoResponder.php';

return $this->privates['App\UI\Responders\AddedVideoResponder'] = new \App\UI\Responders\AddedVideoResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
