<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\AddedTrickResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/AddedTrickResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/AddedTrickResponder.php';

return $this->privates['App\UI\Responders\AddedTrickResponder'] = new \App\UI\Responders\AddedTrickResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
