<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\AddImagesAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/AddImagesActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/AddImagesAction.php';

return $this->services['App\UI\Actions\AddImagesAction'] = new \App\UI\Actions\AddImagesAction(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
