<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\CommentsAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/CommentsActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/CommentsAction.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/CommentDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/CommentDTO.php';

return $this->services['App\UI\Actions\CommentsAction'] = new \App\UI\Actions\CommentsAction(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['session'] ?? $this->load('getSessionService.php')), ($this->privates['App\Domain\DTO\CommentDTO'] ?? $this->privates['App\Domain\DTO\CommentDTO'] = new \App\Domain\DTO\CommentDTO()));
