<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\InscriptionStatusResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/InscriptionStatusResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/InscriptionStatusResponder.php';

return $this->privates['App\UI\Responders\InscriptionStatusResponder'] = new \App\UI\Responders\InscriptionStatusResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
