<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\DTO\ImagesDTO' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/ImagesDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/ImagesDTO.php';

return $this->privates['App\Domain\DTO\ImagesDTO'] = new \App\Domain\DTO\ImagesDTO();
