<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\IndexResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/IndexResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/IndexResponder.php';

return $this->privates['App\UI\Responders\IndexResponder'] = new \App\UI\Responders\IndexResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
