<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Models\Tricks' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Models/Interfaces/TricksInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Models/Tricks.php';

return $this->privates['App\Domain\Models\Tricks'] = new \App\Domain\Models\Tricks();
