<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\DTO\TrickAddDTO' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/TricksAddDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/TrickAddDTO.php';

return $this->privates['App\Domain\DTO\TrickAddDTO'] = new \App\Domain\DTO\TrickAddDTO();
