<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\UpdateTrickAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/UpdateTrickActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/UpdateTrickAction.php';

return $this->services['App\UI\Actions\UpdateTrickAction'] = new \App\UI\Actions\UpdateTrickAction(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
