<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\UpdatedTrickResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/UpdatedTrickResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/UpdatedTrickResponder.php';

return $this->privates['App\UI\Responders\UpdatedTrickResponder'] = new \App\UI\Responders\UpdatedTrickResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
