<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\UI\\Actions\\ALaUneAction:__invoke' => function () {
    return ($this->privates['service_locator.G243FVt'] ?? $this->load('getServiceLocator_G243FVtService.php'));
}, 'App\\UI\\Actions\\AddImagesAction:__invoke' => function () {
    return ($this->privates['service_locator.j4lComi'] ?? $this->load('getServiceLocator_J4lComiService.php'));
}, 'App\\UI\\Actions\\AddTrickAction:__invoke' => function () {
    return ($this->privates['service_locator.CR9c8HC'] ?? $this->load('getServiceLocator_CR9c8HCService.php'));
}, 'App\\UI\\Actions\\CommentsAction:getComments' => function () {
    return ($this->privates['service_locator.RNo9.MG'] ?? $this->load('getServiceLocator_RNo9_MGService.php'));
}, 'App\\UI\\Actions\\ConnectionFormAction:__invoke' => function () {
    return ($this->privates['service_locator.CCt3n1I'] ?? $this->load('getServiceLocator_CCt3n1IService.php'));
}, 'App\\UI\\Actions\\IndexAction:__invoke' => function () {
    return ($this->privates['service_locator.i8XM4.r'] ?? $this->load('getServiceLocator_I8XM4_RService.php'));
}, 'App\\UI\\Actions\\InscriptionFormAction:__invoke' => function () {
    return ($this->privates['service_locator.bsbIov7'] ?? $this->load('getServiceLocator_BsbIov7Service.php'));
}, 'App\\UI\\Actions\\OneTrickAction:__invoke' => function () {
    return ($this->privates['service_locator.xCrgbBD'] ?? $this->load('getServiceLocator_XCrgbBDService.php'));
}, 'App\\UI\\Actions\\ShareVideosAction:__invoke' => function () {
    return ($this->privates['service_locator.mOienZy'] ?? $this->load('getServiceLocator_MOienZyService.php'));
}, 'App\\UI\\Actions\\UpdateTrickAction:__invoke' => function () {
    return ($this->privates['service_locator.M6YvRn4'] ?? $this->load('getServiceLocator_M6YvRn4Service.php'));
}, 'App\\UI\\Actions\\ALaUneAction::__invoke' => function () {
    return ($this->privates['service_locator.G243FVt'] ?? $this->load('getServiceLocator_G243FVtService.php'));
}, 'App\\UI\\Actions\\ALaUneAction' => function () {
    return ($this->privates['service_locator.G243FVt'] ?? $this->load('getServiceLocator_G243FVtService.php'));
}, 'App\\UI\\Actions\\AddImagesAction::__invoke' => function () {
    return ($this->privates['service_locator.j4lComi'] ?? $this->load('getServiceLocator_J4lComiService.php'));
}, 'App\\UI\\Actions\\AddImagesAction' => function () {
    return ($this->privates['service_locator.j4lComi'] ?? $this->load('getServiceLocator_J4lComiService.php'));
}, 'App\\UI\\Actions\\AddTrickAction::__invoke' => function () {
    return ($this->privates['service_locator.CR9c8HC'] ?? $this->load('getServiceLocator_CR9c8HCService.php'));
}, 'App\\UI\\Actions\\AddTrickAction' => function () {
    return ($this->privates['service_locator.CR9c8HC'] ?? $this->load('getServiceLocator_CR9c8HCService.php'));
}, 'App\\UI\\Actions\\CommentsAction::getComments' => function () {
    return ($this->privates['service_locator.RNo9.MG'] ?? $this->load('getServiceLocator_RNo9_MGService.php'));
}, 'App\\UI\\Actions\\ConnectionFormAction::__invoke' => function () {
    return ($this->privates['service_locator.CCt3n1I'] ?? $this->load('getServiceLocator_CCt3n1IService.php'));
}, 'App\\UI\\Actions\\ConnectionFormAction' => function () {
    return ($this->privates['service_locator.CCt3n1I'] ?? $this->load('getServiceLocator_CCt3n1IService.php'));
}, 'App\\UI\\Actions\\IndexAction::__invoke' => function () {
    return ($this->privates['service_locator.i8XM4.r'] ?? $this->load('getServiceLocator_I8XM4_RService.php'));
}, 'App\\UI\\Actions\\IndexAction' => function () {
    return ($this->privates['service_locator.i8XM4.r'] ?? $this->load('getServiceLocator_I8XM4_RService.php'));
}, 'App\\UI\\Actions\\InscriptionFormAction::__invoke' => function () {
    return ($this->privates['service_locator.bsbIov7'] ?? $this->load('getServiceLocator_BsbIov7Service.php'));
}, 'App\\UI\\Actions\\InscriptionFormAction' => function () {
    return ($this->privates['service_locator.bsbIov7'] ?? $this->load('getServiceLocator_BsbIov7Service.php'));
}, 'App\\UI\\Actions\\OneTrickAction::__invoke' => function () {
    return ($this->privates['service_locator.xCrgbBD'] ?? $this->load('getServiceLocator_XCrgbBDService.php'));
}, 'App\\UI\\Actions\\OneTrickAction' => function () {
    return ($this->privates['service_locator.xCrgbBD'] ?? $this->load('getServiceLocator_XCrgbBDService.php'));
}, 'App\\UI\\Actions\\ShareVideosAction::__invoke' => function () {
    return ($this->privates['service_locator.mOienZy'] ?? $this->load('getServiceLocator_MOienZyService.php'));
}, 'App\\UI\\Actions\\ShareVideosAction' => function () {
    return ($this->privates['service_locator.mOienZy'] ?? $this->load('getServiceLocator_MOienZyService.php'));
}, 'App\\UI\\Actions\\UpdateTrickAction::__invoke' => function () {
    return ($this->privates['service_locator.M6YvRn4'] ?? $this->load('getServiceLocator_M6YvRn4Service.php'));
}, 'App\\UI\\Actions\\UpdateTrickAction' => function () {
    return ($this->privates['service_locator.M6YvRn4'] ?? $this->load('getServiceLocator_M6YvRn4Service.php'));
})));
