<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\AddTrickAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/AddTrickActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/AddTrickAction.php';

return $this->services['App\UI\Actions\AddTrickAction'] = new \App\UI\Actions\AddTrickAction(($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
