<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\FormHandler\CommentTypeHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/Interfaces/CommentTypeHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/CommentTypeHandler.php';

return $this->privates['App\Domain\Form\FormHandler\CommentTypeHandler'] = new \App\Domain\Form\FormHandler\CommentTypeHandler(($this->privates['App\Domain\Repository\UsersRepository'] ?? $this->load('getUsersRepositoryService.php')), ($this->privates['App\Domain\Repository\CommentsRepository'] ?? $this->load('getCommentsRepositoryService.php')), ($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')), ($this->services['session'] ?? $this->load('getSessionService.php')));
