<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\FormHandler\InscriptionTypeHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/Interfaces/FormTypeHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/InscriptionTypeHandler.php';

return $this->privates['App\Domain\Form\FormHandler\InscriptionTypeHandler'] = new \App\Domain\Form\FormHandler\InscriptionTypeHandler(($this->privates['App\Domain\Repository\UsersRepository'] ?? $this->load('getUsersRepositoryService.php')));
