<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\InscriptionFormAction' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/InscriptionUserDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/InscriptionUserDTO.php';
include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/InscriptionFormActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/InscriptionFormAction.php';

return $this->services['App\UI\Actions\InscriptionFormAction'] = new \App\UI\Actions\InscriptionFormAction(new \App\Domain\DTO\InscriptionUserDTO(), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['twig'] ?? $this->getTwigService()));
