<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\FormHandler\ImagesTypeHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/Interfaces/ImagesTypeHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/ImagesTypeHandler.php';

return $this->privates['App\Domain\Form\FormHandler\ImagesTypeHandler'] = new \App\Domain\Form\FormHandler\ImagesTypeHandler(($this->privates['App\Domain\Repository\ImagesRepository'] ?? $this->load('getImagesRepositoryService.php')), ($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')), ($this->targetDirs[3].'/public/uploads'));
