<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\OneTrickAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/OneTrickActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/OneTrickAction.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/CommentDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/CommentDTO.php';

return $this->services['App\UI\Actions\OneTrickAction'] = new \App\UI\Actions\OneTrickAction(($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')), ($this->privates['App\Domain\Repository\CommentsRepository'] ?? $this->load('getCommentsRepositoryService.php')), ($this->privates['App\Domain\Repository\ImagesRepository'] ?? $this->load('getImagesRepositoryService.php')), ($this->privates['App\Domain\Repository\VideosRepository'] ?? $this->load('getVideosRepositoryService.php')), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->privates['App\Domain\DTO\CommentDTO'] ?? $this->privates['App\Domain\DTO\CommentDTO'] = new \App\Domain\DTO\CommentDTO()));
