<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.M6YvRn4' shared service.

return $this->privates['service_locator.M6YvRn4'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('trick' => function (): ?\App\Domain\Models\Tricks {
    return ($this->privates['App\Domain\Models\Tricks'] ?? $this->privates['App\Domain\Models\Tricks'] = new \App\Domain\Models\Tricks());
}, 'updateTrickResponder' => function () {
    return ($this->privates['App\UI\Responders\UpdateTrickResponder'] ?? $this->load('getUpdateTrickResponderService.php'));
}, 'updateTrickTypeHandler' => function (): ?\App\Domain\Form\FormHandler\UpdateTrickTypeHandler {
    return ($this->privates['App\Domain\Form\FormHandler\UpdateTrickTypeHandler'] ?? $this->load('getUpdateTrickTypeHandlerService.php'));
}, 'updatedTrickResponder' => function () {
    return ($this->privates['App\UI\Responders\UpdatedTrickResponder'] ?? $this->load('getUpdatedTrickResponderService.php'));
}));
