<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.G243FVt' shared service.

return $this->privates['service_locator.G243FVt'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('aLaUneResponder' => function () {
    return ($this->privates['App\UI\Responders\ALaUneResponder'] ?? $this->load('getALaUneResponderService.php'));
}, 'aLaUneTypeHandler' => function () {
    return ($this->privates['App\Domain\Form\FormHandler\ALaUneTypeHandler'] ?? $this->load('getALaUneTypeHandlerService.php'));
}, 'dto' => function () {
    return ($this->privates['App\Domain\DTO\ALaUneDTO'] ?? $this->privates['App\Domain\DTO\ALaUneDTO'] = new \App\Domain\DTO\ALaUneDTO());
}));
