<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\UpdateTrickResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/UpdateTrickResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/UpdateTrickResponder.php';

return $this->privates['App\UI\Responders\UpdateTrickResponder'] = new \App\UI\Responders\UpdateTrickResponder(($this->services['twig'] ?? $this->getTwigService()));
