<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\FormHandler\UpdateTrickTypeHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/Interfaces/UpdateTrickTypeHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/UpdateTrickTypeHandler.php';

return $this->privates['App\Domain\Form\FormHandler\UpdateTrickTypeHandler'] = new \App\Domain\Form\FormHandler\UpdateTrickTypeHandler(($this->services['session'] ?? $this->load('getSessionService.php')), ($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')), ($this->privates['App\Domain\Repository\UsersRepository'] ?? $this->load('getUsersRepositoryService.php')));
