<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\FormHandler\VideosTypeHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/Interfaces/VideosTypeHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/VideosTypeHandler.php';

return $this->privates['App\Domain\Form\FormHandler\VideosTypeHandler'] = new \App\Domain\Form\FormHandler\VideosTypeHandler(($this->privates['App\Domain\Repository\VideosRepository'] ?? $this->load('getVideosRepositoryService.php')), ($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')));
