<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\DTO\VideosDTO' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/VideosDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/VideosDTO.php';

return $this->privates['App\Domain\DTO\VideosDTO'] = new \App\Domain\DTO\VideosDTO();
