

#blog_list:
#    path:      /blog/{page}
#    controller: App\Controller\BlogController::list
#    defaults:
#        page: 1
#    requirements:
#        page: '\d+'

home:
    path : /
    controller: App\Controller\AllTricksController::showAllTricksAction

singleTrick:
    path : /trick/{id}
    controller: App\Controller\OneTrickController::showTrickAction

connectionForm:
    path : /connexion
    controller: App\Controller\ConnectionFormController::showConnectionForm

