<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\AddTrickResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/AddTrickResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/AddTrickResponder.php';

return $this->privates['App\UI\Responders\AddTrickResponder'] = new \App\UI\Responders\AddTrickResponder(($this->services['twig'] ?? $this->getTwigService()));
