<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\ALaUneResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/ALaUneResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/ALaUneResponder.php';

return $this->privates['App\UI\Responders\ALaUneResponder'] = new \App\UI\Responders\ALaUneResponder(($this->services['twig'] ?? $this->getTwigService()));
