<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\ConnectionFormResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/ConnectionFormResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/ConnectionFormResponder.php';

return $this->privates['App\UI\Responders\ConnectionFormResponder'] = new \App\UI\Responders\ConnectionFormResponder(($this->services['twig'] ?? $this->getTwigService()));
