<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Command/DebugCommand.php';

$this->privates['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(($this->privates['form.registry'] ?? $this->load('getForm_RegistryService.php')), array(0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'App\\Domain\\Form\\Type', 2 => 'Symfony\\Bridge\\Doctrine\\Form\\Type'), array(0 => 'App\\Domain\\Form\\Type\\ALaUneType', 1 => 'App\\Domain\\Form\\Type\\CommentType', 2 => 'App\\Domain\\Form\\Type\\ConnectionType', 3 => 'App\\Domain\\Form\\Type\\ImagesType', 4 => 'App\\Domain\\Form\\Type\\InscriptionType', 5 => 'App\\Domain\\Form\\Type\\TrickType', 6 => 'App\\Domain\\Form\\Type\\UpdateTrickType', 7 => 'App\\Domain\\Form\\Type\\VideosType', 8 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 9 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 10 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType'), array(0 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 1 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 4 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\UploadValidatorExtension', 5 => 'Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension', 6 => 'Symfony\\Component\\Form\\Extension\\DataCollector\\Type\\DataCollectorTypeExtension'), array(0 => 'Symfony\\Component\\Form\\Extension\\Validator\\ValidatorTypeGuesser', 1 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser'));

$instance->setName('debug:form');

return $instance;
