<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\FormLoginAuthenticator' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Http/EntryPoint/AuthenticationEntryPointInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Guard/AuthenticatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Guard/AbstractGuardAuthenticator.php';
include_once $this->targetDirs[3].'/src/Security/FormLoginAuthenticator.php';

return $this->privates['App\Security\FormLoginAuthenticator'] = new \App\Security\FormLoginAuthenticator(($this->services['session'] ?? $this->load('getSessionService.php')), ($this->services['router'] ?? $this->getRouterService()));
