<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.xCrgbBD' shared service.

return $this->privates['service_locator.xCrgbBD'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('commentTypeHandler' => function (): ?\App\Domain\Form\FormHandler\CommentTypeHandler {
    return ($this->privates['App\Domain\Form\FormHandler\CommentTypeHandler'] ?? $this->load('getCommentTypeHandlerService.php'));
}, 'oneTrickResponder' => function () {
    return ($this->privates['App\UI\Responders\OneTrickResponder'] ?? $this->load('getOneTrickResponderService.php'));
}, 'session' => function () {
    return ($this->services['session'] ?? $this->load('getSessionService.php'));
}));
