<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.CR9c8HC' shared service.

return $this->privates['service_locator.CR9c8HC'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('TrickTypeHandler' => function () {
    return ($this->privates['App\Domain\Form\FormHandler\TrickTypeHandler'] ?? $this->load('getTrickTypeHandlerService.php'));
}, 'addTrickResponder' => function () {
    return ($this->privates['App\UI\Responders\AddTrickResponder'] ?? $this->load('getAddTrickResponderService.php'));
}, 'addedTrickResponder' => function () {
    return ($this->privates['App\UI\Responders\AddedTrickResponder'] ?? $this->load('getAddedTrickResponderService.php'));
}, 'trickDto' => function () {
    return ($this->privates['App\Domain\DTO\TrickAddDTO'] ?? $this->privates['App\Domain\DTO\TrickAddDTO'] = new \App\Domain\DTO\TrickAddDTO());
}));
