<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.i8XM4.r' shared service.

return $this->privates['service_locator.i8XM4.r'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('indexResponder' => function () {
    return ($this->privates['App\UI\Responders\IndexResponder'] ?? $this->load('getIndexResponderService.php'));
}));
