<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\ALaUneAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/ALaUneActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/ALaUneAction.php';

return $this->services['App\UI\Actions\ALaUneAction'] = new \App\UI\Actions\ALaUneAction(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')));
