<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\FormHandler\ALaUneTypeHandler' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/Interfaces/ALaUneTypeHandlerInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/FormHandler/ALaUneTypeHandler.php';

return $this->privates['App\Domain\Form\FormHandler\ALaUneTypeHandler'] = new \App\Domain\Form\FormHandler\ALaUneTypeHandler(($this->privates['App\Domain\Repository\ImagesRepository'] ?? $this->load('getImagesRepositoryService.php')));
