<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\DTO\ALaUneDTO' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/DTO/Interfaces/ALaUneDTOInterface.php';
include_once $this->targetDirs[3].'/src/Domain/DTO/ALaUneDTO.php';

return $this->privates['App\Domain\DTO\ALaUneDTO'] = new \App\Domain\DTO\ALaUneDTO();
