<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\AddedImagesResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/AddedImagesResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/AddedImagesResponder.php';

return $this->privates['App\UI\Responders\AddedImagesResponder'] = new \App\UI\Responders\AddedImagesResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
