<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Form\Type\CommentType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Domain/Form/Type/Interfaces/FormTypeInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Form/Type/CommentType.php';

return $this->privates['App\Domain\Form\Type\CommentType'] = new \App\Domain\Form\Type\CommentType();
