<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Repository\CommentsRepository' shared autowired service.

include_once $this->targetDirs[3].'/vendor/doctrine/common/lib/Doctrine/Common/Persistence/ObjectRepository.php';
include_once $this->targetDirs[3].'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
include_once $this->targetDirs[3].'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
include_once $this->targetDirs[3].'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
include_once $this->targetDirs[3].'/src/Domain/Repository/Interfaces/CommentsRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Repository/CommentsRepository.php';

return $this->privates['App\Domain\Repository\CommentsRepository'] = new \App\Domain\Repository\CommentsRepository(($this->services['doctrine'] ?? $this->load('getDoctrineService.php')));
