<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\CommentsResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/CommentsResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/CommentsResponder.php';

return $this->privates['App\UI\Responders\CommentsResponder'] = new \App\UI\Responders\CommentsResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
