<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\ConnectionFormAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/ConnectionFormActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/ConnectionFormAction.php';

return $this->services['App\UI\Actions\ConnectionFormAction'] = new \App\UI\Actions\ConnectionFormAction();
