<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\DeleteTrickAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/DeleteTrickActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/DeleteTrickAction.php';

return $this->services['App\UI\Actions\DeleteTrickAction'] = new \App\UI\Actions\DeleteTrickAction(($this->privates['App\Domain\Repository\TricksRepository'] ?? $this->load('getTricksRepositoryService.php')));
