<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\UI\Actions\DeleteVideoAction' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Actions/Interfaces/DeleteVideoActionInterface.php';
include_once $this->targetDirs[3].'/src/UI/Actions/DeleteVideoAction.php';

return $this->services['App\UI\Actions\DeleteVideoAction'] = new \App\UI\Actions\DeleteVideoAction(($this->privates['App\Domain\Repository\VideosRepository'] ?? $this->load('getVideosRepositoryService.php')));
