<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\InscriptionFormResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/InscriptionFormResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/InscriptionFormResponder.php';

return $this->privates['App\UI\Responders\InscriptionFormResponder'] = new \App\UI\Responders\InscriptionFormResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
