<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\UI\Responders\OneTrickResponder' shared autowired service.

include_once $this->targetDirs[3].'/src/UI/Responders/Interfaces/OneTrickResponderInterface.php';
include_once $this->targetDirs[3].'/src/UI/Responders/OneTrickResponder.php';

return $this->privates['App\UI\Responders\OneTrickResponder'] = new \App\UI\Responders\OneTrickResponder(($this->services['twig'] ?? $this->load('getTwigService.php')));
