<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.j4lComi' shared service.

return $this->privates['service_locator.j4lComi'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('addImagesResponder' => function () {
    return ($this->privates['App\UI\Responders\AddImagesResponder'] ?? $this->load('getAddImagesResponderService.php'));
}, 'addedImagesResponder' => function () {
    return ($this->privates['App\UI\Responders\AddedImagesResponder'] ?? $this->load('getAddedImagesResponderService.php'));
}, 'imagesDto' => function () {
    return ($this->privates['App\Domain\DTO\ImagesDTO'] ?? $this->privates['App\Domain\DTO\ImagesDTO'] = new \App\Domain\DTO\ImagesDTO());
}, 'imagesHandler' => function () {
    return ($this->privates['App\Domain\Form\FormHandler\ImagesTypeHandler'] ?? $this->load('getImagesTypeHandlerService.php'));
}));
