<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.RNo9.MG' shared service.

return $this->privates['service_locator.RNo9.MG'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('commentTypeHandler' => function () {
    return ($this->privates['App\Domain\Form\FormHandler\CommentTypeHandler'] ?? $this->load('getCommentTypeHandlerService.php'));
}, 'commentsResponder' => function () {
    return ($this->privates['App\UI\Responders\CommentsResponder'] ?? $this->load('getCommentsResponderService.php'));
}));
