<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.bsbIov7' shared service.

return $this->privates['service_locator.bsbIov7'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('InscriptionTypeHandler' => function (): ?\App\Domain\Form\FormHandler\InscriptionTypeHandler {
    return ($this->privates['App\Domain\Form\FormHandler\InscriptionTypeHandler'] ?? $this->load('getInscriptionTypeHandlerService.php'));
}, 'inscriptionFormResponder' => function () {
    return ($this->privates['App\UI\Responders\InscriptionFormResponder'] ?? $this->load('getInscriptionFormResponderService.php'));
}, 'inscriptionStatusResponder' => function () {
    return ($this->privates['App\UI\Responders\InscriptionStatusResponder'] ?? $this->load('getInscriptionStatusResponderService.php'));
}));
