<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.CCt3n1I' shared service.

return $this->privates['service_locator.CCt3n1I'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('connectionFormResponder' => function (): ?\App\UI\Responders\ConnectionFormResponder {
    return ($this->privates['App\UI\Responders\ConnectionFormResponder'] ?? $this->load('getConnectionFormResponderService.php'));
}));
