<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMLD8xxv\srcTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMLD8xxv/srcTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMLD8xxv.legacy');

    return;
}

if (!\class_exists(srcTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMLD8xxv\srcTestDebugProjectContainer::class, srcTestDebugProjectContainer::class, false);
}

return new \ContainerMLD8xxv\srcTestDebugProjectContainer(array(
    'container.build_hash' => 'MLD8xxv',
    'container.build_id' => '46381af5',
    'container.build_time' => 1525435609,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMLD8xxv');
