<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4RxMAJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4RxMAJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ4RxMAJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ4RxMAJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZ4RxMAJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Z4RxMAJ',
    'container.build_id' => '146c4119',
    'container.build_time' => 1525708027,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4RxMAJ');
